version: '3.3'
services:
  backend:
    build:
      context: ../backend
    command: /start-reload.sh
    ports:
      - "80:80"
    restart: always
    env_file:
      - backend.env
      - postgres.env
    depends_on:
      - db
    volumes:
      - ../backend/app:/app

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - postgres.env


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-data: