"""empty message

Revision ID: 08781b5994f9
Revises: 7440551a6d7e
Create Date: 2019-09-28 15:04:19.448824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08781b5994f9'
down_revision = '7440551a6d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_partner_associations',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'partner_id')
    )
    op.add_column('partners', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('partners', 'phone')
    op.alter_column('volunteers', 'additional_skills',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('volunteers', 'children_work_experience',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('volunteers', 'cloth_size',
               existing_type=postgresql.ENUM('XS', 'S', 'M', 'L', 'XL', 'XXL', name='clothsize'),
               nullable=True)
    op.alter_column('volunteers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('volunteers', 'interested_in_projects',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('volunteers', 'known_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('volunteers', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('volunteers', 'reasons_to_work',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('volunteers', 'volunteer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('volunteers', 'work',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteers', 'work',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volunteers', 'volunteer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volunteers', 'reasons_to_work',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volunteers', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('volunteers', 'known_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('volunteers', 'interested_in_projects',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('volunteers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('volunteers', 'cloth_size',
               existing_type=postgresql.ENUM('XS', 'S', 'M', 'L', 'XL', 'XXL', name='clothsize'),
               nullable=False)
    op.alter_column('volunteers', 'children_work_experience',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('volunteers', 'additional_skills',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('partners', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('partners', 'phone_number')
    op.drop_table('event_partner_associations')
    # ### end Alembic commands ###
