"""photos

Revision ID: 181e452b6458
Revises: d3d33e32795b
Create Date: 2019-09-29 02:14:19.899410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181e452b6458'
down_revision = 'd3d33e32795b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('location', sa.String(), nullable=False))
    op.alter_column('volunteers', 'volunteer_id',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=5),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteers', 'volunteer_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('events', 'location')
    op.drop_table('photos')
    # ### end Alembic commands ###
