"""event_tag

Revision ID: 276fdab8688b
Revises: f3a6316ebf6e
Create Date: 2019-09-29 02:51:33.765268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276fdab8688b'
down_revision = 'f3a6316ebf6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_tags',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_tags')
    # ### end Alembic commands ###
