"""empty message

Revision ID: c3fb8f766f93
Revises: 0a5a19a0c68b
Create Date: 2019-09-27 20:12:40.944416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fb8f766f93'
down_revision = '0a5a19a0c68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('karma_to_pay', sa.Integer(), nullable=False),
    sa.Column('need_paper_certificate', sa.Boolean(), nullable=False),
    sa.Column('motivation', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('participation_status', sa.Enum('APPROVED', 'WAITING', 'KICKED', 'DECLINED', 'PLANNED', name='participationstatus'), nullable=False),
    sa.Column('actual_role_id', sa.Integer(), nullable=True),
    sa.Column('preferable_role1_id', sa.Integer(), nullable=True),
    sa.Column('preferable_role2_id', sa.Integer(), nullable=True),
    sa.Column('preferable_role3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actual_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['preferable_role1_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['preferable_role2_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['preferable_role3_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('organizer_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_event_id'], ['organizers_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('qr_data', sa.Column('event_volunteer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'qr_data', 'events_volunteers', ['event_volunteer_id'], ['id'])
    op.add_column('roles', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('roles', sa.Column('max_people', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'roles', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'max_people')
    op.drop_column('roles', 'event_id')
    op.drop_constraint(None, 'qr_data', type_='foreignkey')
    op.drop_column('qr_data', 'event_volunteer_id')
    op.drop_table('todos')
    op.drop_table('events_volunteers')
    # ### end Alembic commands ###
