"""age restriction

Revision ID: f7977c9fa185
Revises: 08781b5994f9
Create Date: 2019-09-28 15:54:20.705962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7977c9fa185'
down_revision = '08781b5994f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('age_restriction', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'age_restriction')
    # ### end Alembic commands ###
